### ISSUE TITLE
1. Tambahkan Slide Foto

### ISSUE THREAD

**Issue by widoyo** [rpahlevy/sargede#57]
Halaman Home foto lebih dari 1 (3 foto/fleksible) auto sliding

**Comment by widoyo** [comment]
Sebenarnya permintaannya User bisa mengganti Foto-foto scrolling sendiri

**Comment by rpahlevy** [comment]
perlu di develop fiturnya nggak pak @widoyo 
> User bisa mengganti Foto-foto scrolling sendiri

**Comment by widoyo** [comment]
Perlu, admin bisa ngganti foto² slide

**Comment by rpahlevy** [comment]
di reopen atau issue baru saja ya pak?

**Comment by widoyo** [comment]
Issue baru: CMS utk Carousel Foto
